#!/bin/sh
#Copies dll from MSYS2 to make standalone packages
#Default is Windows Default

filesdef=(
    "libaom.dll"
    "libatk-1.0-0.dll"
    "libavif-16.dll"
    "libbrotlicommon.dll"
    "libbrotlidec.dll"
    "libbrotlienc.dll"
    "libbz2-1.dll"
    "libcacard-0.dll"
    "libcairo-2.dll"
    "libcairo-gobject-2.dll"
    "libcapstone.dll"
    "libcrypto-3-x64.dll"
    "libcurl-4.dll"
    "libdatrie-1.dll"
    "libdav1d-7.dll"
    "libdb-6.0.dll"
    "libdeflate.dll"
    "libepoxy-0.dll"
    "libexpat-1.dll"
    "libfdt-1.dll"
    "libffi-8.dll"
    "libfontconfig-1.dll"
    "libfreetype-6.dll"
    "libfribidi-0.dll"
    "libgcc_s_seh-1.dll"
    "libgdk_pixbuf-2.0-0.dll"
    "libgdk-3-0.dll"
    "libgio-2.0-0.dll"
    "libglib-2.0-0.dll"
    "libgmodule-2.0-0.dll"
    "libgmp-10.dll"
    "libgnutls-30.dll"
    "libgobject-2.0-0.dll"
    "libgraphite2.dll"
    "libgstapp-1.0-0.dll"
    "libgstbase-1.0-0.dll"
    "libgstreamer-1.0-0.dll"
    "libgtk-3-0.dll"
    "libharfbuzz-0.dll"
    "libhogweed-6.dll"
    "libhwy.dll"
    "libiconv-2.dll"
    "libidn-12.dll"
    "libidn2-0.dll"
    "libintl-8.dll"
    "libjack64.dll"
    "libjbig-0.dll"
    "libjpeg-8.dll"
    "libjxl.dll"
    "libjxl_cms.dll"
    "liblcms2-2.dll"
    "libLerc.dll"
    "liblz4.dll"
    "liblzma-5.dll"
    "liblzo2-2.dll"
    "libncursesw6.dll"
    "libnettle-8.dll"
    "libnfs-14.dll"
    "libnghttp2-14.dll"
    "libnghttp3-9.dll"
    "libnspr4.dll"
    "libopus-0.dll"
    "liborc-0.4-0.dll"
    "libp11-kit-0.dll"
    "libpango-1.0-0.dll"
    "libpangocairo-1.0-0.dll"
    "libpangoft2-1.0-0.dll"
    "libpangowin32-1.0-0.dll"
    "libpcre2-8-0.dll"
    "libpixman-1-0.dll"
    "libplc4.dll"
    "libplds4.dll"
    "libpng16-16.dll"
    "libproxy-1.dll"
    "libpsl-5.dll"
    "libsasl2-3.dll"
    "libsharpyuv-0.dll"
    "libslirp-0.dll"
    "libsnappy.dll"
    "libspice-server-1.dll"
    "libssh.dll"
    "libssh2-1.dll"
    "libssl-3-x64.dll"
    "libstdc++-6.dll"
    "libSvtAv1Enc-2.dll"
    "libsystre-0.dll"
    "libtasn1-6.dll"
    "libthai-0.dll"
    "libtiff-6.dll"
    "libtre-5.dll"
    "libunistring-5.dll"
    "libusb-1.0.dll"
    "libusbredirparser-1.dll"
    "libvirglrenderer-1.dll"
    "libwebp-7.dll"
    "libwebpdemux-2.dll"
    "libwinpthread-1.dll"
    "libyuv.dll"
    "libzstd.dll"
    "nss3.dll"
    "nssutil3.dll"
    "librav1e.dll"
    "SDL2.dll"
    "SDL2_image.dll"
    "zlib1.dll"
)
if [[ -z "$MSYSTEM" ]]; then
    echo "you running MSYS2?" >&2
    exit 1
fi

case "$MSYSTEM" in
    UCRT64)
        echo "Running in UCRT64 environment."
        ;;
    MINGW64)
        echo "Running in MINGW64 environment."
        ;;
    *)
        echo "Running in an unsupported or unrecognized MSYS2 environment: $MSYSTEM" >&2
        exit 1
        ;;
esac

echo "Copying files"

for filedef in "${filesdef[@]}"; do
    if [[ -f "$MINGW_PREFIX/bin/$filedef" ]]; then
        cp "$MINGW_PREFIX/bin/$filedef" ./
    else
        echo "Error: $filedef is missing!" >&2
    fi
done
echo "Done!"