#!/bin/sh
# This script is used to sign the binary with the build timestamp and version

platform='unknown'
unamestr=$(uname -o)

# Check if the folder it checks is in iso folder
if [ -f "$(pwd)/qemu.ico" ] || [ -f "$(pwd)/open.bat" ] || [ -f "$(pwd)/autorun.inf" ]; then
   platform='wrappers'
   echo "Wrappers found!"
# Check the right platform   
elif [[ "$unamestr" == 'GNU/Linux' ]]; then
   if [ -f /etc/arch-release ]; then
      platform='arch'
      echo "Arch Linux"
   elif [ -f /etc/debian_version ]; then
      platform='debian'
      echo "Debian not supported yet"
      exit 1
   elif [ -f /etc/ubuntu_version ]; then
      platform='ubuntu'
      echo "Ubuntu not supported yet"
      exit 1
   else
      echo "Unknown Linux distribution or not supported"
      exit 1
   fi
   echo Linux
elif [[ "$unamestr" == 'Msys' ]]; then
   if ! command -v pacman 2>&1 >/dev/null
   then
      echo "pacman not found! Are you are running in Git Bash?"
      exit 1
   else
      platform='windows'
      echo "Windows"
   fi
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='mac'
   echo "MacOS not supported yet..."
   exit 1
else 
   echo "Unknown platform"
   exit 1
fi

## Signing iso
if [[ $platform == 'wrappers' ]]; then
cat <<EOF > commit\ id.txt
QEMU-3dfx-arch VMAddons ISO
=================================================
Commit $(git rev-parse HEAD)

refer to readme.txt for more information
EOF
echo "Signed commit id.txt"
fi
## Signing binaries
if [[ $platform == 'windows' ]]; then
cat <<EOF > build-timestamp.txt 
Built on $(date +"%H:%M:%S %B %d %Y") 
  $(pacman -Q binutils) 
  $(pacman -Q git) 
  $(pacman -Q gcc)
EOF
echo "Signed build-timestamp.txt"


cat <<EOF > version.txt
QEMU-3dfx-arch (Windows build)
=================================================
Version $(git describe --tags)
Built using ${MSYSTEM}
EOF
echo "Signed version.txt"
exit 0

elif [[ $platform == 'arch' ]]; then
cat <<EOF > build-timestamp.txt 
Built on $(date +"%H:%M:%S %B %d %Y") 
  $(pacman -Q binutils) 
  $(pacman -Q git) 
  $(pacman -Q gcc)
EOF
echo "Signed build-timestamp.txt"


cat <<EOF > version.txt
QEMU-3dfx-arch (Arch Linux build)
=================================================
Version $(git describe --tags)
Built using GCC $(gcc --version | head -n 1 | cut -d '' -f 3)
EOF
echo "Signed version.txt"
fi
exit 0
